name: "SAP - Publish to Local Maven"
description: "Publishes artifacts to a local Maven repository."
inputs:
  version:
    description: "The version of the artifact to publish."
    required: true
  revision:
    description: "The revision of the artifact to publish."
    required: true
    default: "0"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v5
      with:
        distribution: temurin
        java-version: 21
    - id: publish-security-analytics-commons
      shell: bash
      working-directory: ./commons/
      run: ../gradlew publishToMavenLocal -x check -Dversion=${{ inputs.version }} -Drevision=${{ inputs.revision || '0' }}

    - id: publish-security-analytics
      shell: bash
      working-directory: ./
      run: ./gradlew publishToMavenLocal -x check -Dversion=${{ inputs.version }} -Drevision=${{ inputs.revision || '0' }}
