name: (5.x) Check email
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled, unlabeled]

jobs:
  # Checks if the email domain is @wazuh.com, if not the workflow will fail
  verify-email:
    if: github.repository == 'wazuh/wazuh-indexer-security-analytics'
    runs-on: ubuntu-24.04
    steps:
      - uses: wazuh/wazuh-indexer/.github/actions/5_codeanalysis_emailchecker@main
        with:
            email_domain: 'wazuh.com, @users.noreply.github.com'
            github_token: ${{ secrets.GITHUB_TOKEN }}
            error_on_fail: 'true'
